name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: line script1
      run: echo It is first line!
    
    - name: line script2
      run: |
        echo It is second script!
        echo And the last one!
    
