name: Telegram notification for test_work

on:
    push:
        branches: 
            - test_work

jobs:
    send_message_to_alex:
        runs-on: ubuntu-latest
        steps:
            - name: Send message to Telegram Alex
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                    🚀 Push в ветку: ${{ github.ref_name }} 🚀
                    Автор: ${{ github.actor }}
                    Коммит: ${{ github.sha }}
                    Сообщение коммита: ${{ github.event.head_commit.message }}
    
    send_message_to_ann:
        runs-on: ubuntu-latest
        steps:
            - name: Send message to Telegram Ann
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_ANN }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                    Ваш парень сделал push в ветку: ${{ github.ref_name }} 🚀
                    Сообщение коммита: ${{ github.event.head_commit.message }}